server:
  port: 8080

spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.126.92.128:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: springcloud
    password: springcloud
  jpa:
    show-sql: true
  druid:
    initial-size: 5
    min-idle: 5
    max-active: 20
    test-on-borrow: true
    stat-view-servlet.allow: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
      
